version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  flyway:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://db:5432/${DB_DATABASE} -schemas=myschema -user=${DB_USER} -password=${DB_PASSWORD} -connectRetries=60 migrate
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - db
